project:
  type: website
  output-dir: docs

website:
  title: "Mike Konczal"

  page-footer:
    right: |
      <span class="container">Made with [Quarto](https://quarto.org/){target="_blank"} ([This Site's Repo](https://github.com/mtkonczal/mtkonczal.github.io){target="_blank"})</span>

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: writings.qmd
        text: Writing
      - href: clips.qmd
        text: Clips
      - href: freedom_from_the_market.qmd
        text: Book
  search:
    location: navbar
    type: overlay

format:
  html:
    theme: flatly
    css: styles.css
    toc: false
    page-layout: full
