project:
  type: website
  output-dir: docs

website:
  title: "Mike Konczal"
  
  page-footer:
    right: |
      <span class="container">Made with [Quarto](https://quarto.org/){target="_blank"} ([This Site's Repo](https://github.com/mtkonczal/mtkonczal.github.io){target="_blank"})</span>
    
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: the_book.qmd
        text: The Book
      - href: writings.qmd
        text: Writings
      - href: appearances.qmd
        text: Media Hits
      - href: media.qmd
        text: Media Quotes
      - href: resume.qmd
        text: Resume

  search: 
    location: navbar
    type: overlay
    
format:
  html:
    theme: spacelab
    css: styles.css
    toc: false
    page-layout: full