project:
  type: website
  output-dir: docs

website:
  title: "Mike Konczal"
  
  page-footer:
    right: |
      <span class="container">Made with [Quarto](https://quarto.org/){target="_blank"} ([This Site's Repo](https://github.com/mtkonczal/mtkonczal.github.io){target="_blank"})</span>
    
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: Writings
        menu:
        - href: the_book.qmd
          text: Book
        - href: writings.qmd
          text: Writings
        - href: research.qmd
          text: Research
      - text: Media
        menu:
        - href: appearances.qmd
          text: Media
        - href: media.qmd
          text: Quotes
      - href: resume.qmd
        text: Resume
      - text: Data Analysis
        menu:
        - href: cpi.qmd
          text: CPI Inflation


  search: 
    location: navbar
    type: overlay
    
format:
  html:
    theme: spacelab
    css: styles.css
    toc: false
    page-layout: full