project:
  type: website
  output-dir: docs

website:
  title: "Mike Konczal"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - the_book.qmd
      - writings.qmd
      - resume.qmd
      - href: "https://mikekonczal.substack.com/"
        text: My Substack

format:
  html:
    theme: sandstone
    css: styles.css
    toc: false
    page-layout: full



