---
title: "About"
---

Mike Konczal is the director of Macroeconomic Analysis at the Roosevelt Institute, where he focuses on full employment, inequality, and the role of public power in a democracy. He is the author of *Freedom from the Market: America's Fight to Liberate Itself from the Grip of the Invisible Hand*, and a co-author, with Joseph Stiglitz, of *Rewriting the Rules of the American Economy*. His work has ranged from policy briefs on financial reform to original economic research on austerity and labor market dynamism. A former financial engineer, he holds a B.A. in math and computer science and a M.S. in finance from the University of Illinois at Urbana-Champaign.

Described as having "a cult following among progressives" by the *New York Times Magazine*, his writing has been featured in the *Washington Post*, *Rolling Stone*, *Vox*, *The American Prospect*, *Boston Review*, and more. He is an economics columnist for *The Nation* and a contributing editor at *Dissent*. He is a sought-after commentator on the U.S. economy, cited as an expert in hundreds of press articles, and has appeared on *CBS Sunday Morning*, *All Things Considered*, *Planet Money*, and *Lovett or Leave It*. Born and raised in Chicago, he now lives in Takoma Park, Maryland, with his wife, two daughters, and pit bull.
